In [1]:
import numpy as np
import yfinance as yf

from docplex.mp.model import Model

In [2]:
tickers = ["MSTR", "KO", "V", "NVDA", "CCJ", "ADBE", "JNJ", "JPM"]
assets_data = yf.download(tickers=tickers, period="1y")

[*********************100%***********************]  8 of 8 completed

In [3]:
assets_data

Price            Close                                                 \
Ticker            ADBE         CCJ         JNJ         JPM         KO
Date
2025-05-01  374.630005   45.421558  150.273102  242.180084  69.281616
2025-05-02  380.869995   46.918644  151.888092  247.692856  69.631477
2025-05-05  381.059998   46.319813  150.798462  247.741913  69.680069
2025-05-06  382.980011   48.056431  150.282822  244.495056  69.699501
2025-05-07  384.970001   49.643341  153.036118  244.632385  70.360352
...                ...         ...         ...         ...        ...
2026-04-24  245.440002  122.150002  227.500000  308.279999  76.629997
2026-04-27  239.309998  123.110001  225.339996  311.630005  75.440002
2026-04-28  243.199997  116.309998  227.789993  311.450012  78.349998
2026-04-29  243.570007  114.290001  227.350006  309.250000  78.870003
2026-04-30  246.100006  123.040001  229.850006  313.230011  78.760002

Price                                                 High              ...  \
Ticker            MSTR        NVDA           V        ADBE         CCJ  ...
Date                                                                    ...
2025-05-01  381.600006  111.583702  339.906128  380.440002   46.439577  ...
2025-05-02  394.369995  114.473030  345.017853  383.559998   47.647229  ...
2025-05-05  386.529999  113.793182  346.050140  384.540009   46.709054  ...
2025-05-06  385.600006  113.513260  345.117157  386.519989   48.385788  ...
2025-05-07  392.480011  117.032425  347.251160  387.829987   49.872894  ...
...                ...         ...         ...         ...         ...  ...
2026-04-24  171.020004  208.270004  309.420013  245.660004  125.599998  ...
2026-04-27  169.199997  216.610001  309.649994  245.880005  124.809998  ...
2026-04-28  165.710007  213.169998  309.299988  245.259995  121.790001  ...
2026-04-29  158.190002  209.250000  334.859985  243.619995  116.919998  ...
2026-04-30  165.449997  199.570007  329.839996  246.679993  123.139999  ...

Price             Open               Volume                             \
Ticker            NVDA           V     ADBE      CCJ      JNJ      JPM
Date
2025-05-01  113.053357  343.012851  2848800  4882000  7325800  8689600
2025-05-02  114.153106  344.640671  2340700  4139000  5974500  7165000
2025-05-05  112.883401  344.422309  2095600  2692200  5464100  5450700
2025-05-06  111.453748  343.826796  2970100  5743300  8644200  6369900
2025-05-07  113.023375  346.109708  2153000  5395200  7853100  8724100
...                ...         ...      ...      ...      ...      ...
2026-04-24  199.960007  307.100006  6492900  2285300  6067500  5215300
2026-04-27  209.649994  307.510010  5067700  1982700  7897800  7925300
2026-04-28  209.490005  312.200012  4641700  3167600  7179800  7398600
2026-04-29  212.699997  336.399994  2664500  2273800  7071100  8031800
2026-04-30  209.938995  332.119995  5104010  2606787  8143777  4756521

Price
Ticker            KO      MSTR       NVDA         V
Date
2025-05-01  18034200  16944100  236121500   5849900
2025-05-02  12629600  15948000  190194800   6113700
2025-05-05  11932700  14424100  133163200   3865300
2025-05-06  12705500   9695600  158525600   3438500
2025-05-07  15018200  10555300  206758800   5454000
...              ...       ...        ...       ...
2026-04-24  12008700  14119400  214134400   5616900
2026-04-27  15812200  13295400  187172400   6261500
2026-04-28  30710700  13858700  180275400   8839900
2026-04-29  18294700  15146200  123711800  16658600
2026-04-30  10569924  12286092  223736943  11205927

[251 rows x 40 columns]

In [4]:
assets_close_price = assets_data["Close"]

In [5]:
assets_close_price

Ticker,ADBE,CCJ,JNJ,JPM,KO,MSTR,NVDA,V
Date,,,,,,,,
2025-05-01,374.630005,45.421558,150.273102,242.180084,69.281616,381.600006,111.583702,339.906128
2025-05-02,380.869995,46.918644,151.888092,247.692856,69.631477,394.369995,114.473030,345.017853
2025-05-05,381.059998,46.319813,150.798462,247.741913,69.680069,386.529999,113.793182,346.050140
2025-05-06,382.980011,48.056431,150.282822,244.495056,69.699501,385.600006,113.513260,345.117157
2025-05-07,384.970001,49.643341,153.036118,244.632385,70.360352,392.480011,117.032425,347.251160
...,...,...,...,...,...,...,...,...
2026-04-24,245.440002,122.150002,227.500000,308.279999,76.629997,171.020004,208.270004,309.420013
2026-04-27,239.309998,123.110001,225.339996,311.630005,75.440002,169.199997,216.610001,309.649994
2026-04-28,243.199997,116.309998,227.789993,311.450012,78.349998,165.710007,213.169998,309.299988
2026-04-29,243.570007,114.290001,227.350006,309.250000,78.870003,158.190002,209.250000,334.859985
2026-04-30,246.100006,123.040001,229.850006,313.230011,78.760002,165.449997,199.570007,329.839996

In [6]:
assets_pct_change = assets_close_price.pct_change().dropna()

In [7]:
assets_pct_change

Ticker,ADBE,CCJ,JNJ,JPM,KO,MSTR,NVDA,V
Date,,,,,,,,
2025-05-02,0.016656,0.032960,0.010747,0.022763,0.005050,0.033464,0.025894,0.015039
2025-05-05,0.000499,-0.012763,-0.007174,0.000198,0.000698,-0.019880,-0.005939,0.002992
2025-05-06,0.005039,0.037492,-0.003419,-0.013106,0.000279,-0.002406,-0.002460,-0.002696
2025-05-07,0.005196,0.033022,0.018321,0.000562,0.009481,0.017842,0.031002,0.006183
2025-05-08,-0.002546,-0.010052,-0.010426,0.016360,-0.016989,0.055799,0.002648,0.004059
...,...,...,...,...,...,...,...,...
2026-04-24,0.027032,-0.013726,-0.013657,-0.010940,0.004588,-0.008407,0.043228,0.001748
2026-04-27,-0.024976,0.007859,-0.009495,0.010867,-0.015529,-0.010642,0.040044,0.000743
2026-04-28,0.016255,-0.055235,0.010872,-0.000578,0.038574,-0.020626,-0.015881,-0.001130
2026-04-29,0.001521,-0.017367,-0.001932,-0.007064,0.006637,-0.045381,-0.018389,0.082638
2026-04-30,0.010387,0.076560,0.010996,0.012870,-0.001395,0.045894,-0.046260,-0.014991

In [8]:
covariance_annualized = assets_pct_change.cov()*np.sqrt(252)
returns_annualized = assets_pct_change.mean()*252

In [9]:
covariance_annualized

Ticker,ADBE,CCJ,JNJ,JPM,KO,MSTR,NVDA,V
Ticker,,,,,,,,
ADBE,0.006225,-0.000172,-0.000290,0.000523,-0.000038,0.001426,0.000086,0.001543
CCJ,-0.000172,0.018760,-0.000300,0.002047,-0.000678,0.005295,0.004584,0.000316
JNJ,-0.000290,-0.000300,0.001786,-0.000053,0.000584,-0.000670,-0.000614,0.000268
JPM,0.000523,0.002047,-0.000053,0.002813,-0.000186,0.002200,0.001392,0.001081
KO,-0.000038,-0.000678,0.000584,-0.000186,0.001642,-0.000983,-0.000860,0.000161
MSTR,0.001426,0.005295,-0.000670,0.002200,-0.000983,0.029649,0.005581,0.000157
NVDA,0.000086,0.004584,-0.000614,0.001392,-0.000860,0.005581,0.007259,0.000123
V,0.001543,0.000316,0.000268,0.001081,0.000161,0.000157,0.000123,0.003055

In [10]:
returns_annualized

Ticker
ADBE   -0.373537
CCJ     1.150545
JNJ     0.442769
JPM     0.281762
KO      0.142204
MSTR   -0.609495
NVDA    0.643915
V      -0.006222
dtype: float64

In [11]:
q = 0.5
b = 3
return_risk_free = 0.0375
weights_array = np.array([1/b for _ in range(len(tickers))])

In [12]:
model = Model(name="combinatorial_portfolio_optimization")
x = np.array([model.binary_var(name=f"x[{i}]") for i in range(len(tickers))])
model.minimize(q*((x*weights_array).T@covariance_annualized.values@(x*weights_array))-(1-q)*(returns_annualized.values@x)+return_risk_free)
model.add_constraint(x.sum() == b)
print(model.prettyprint())

// This file has been generated by DOcplex
// model name is: combinatorial_portfolio_optimization
// single vars section
dvar bool x[0];
dvar bool x[1];
dvar bool x[2];
dvar bool x[3];
dvar bool x[4];
dvar bool x[5];
dvar bool x[6];
dvar bool x[7];

minimize
 0.186768 x[0] - 0.575272 x[1] - 0.221385 x[2] - 0.140881 x[3] - 0.071102 x[4]
 + 0.304747 x[5] - 0.321957 x[6] + 0.003111 x[7] [ 0.000346 x[0]^2
 - 0.000019 x[0]*x[1] - 0.000032 x[0]*x[2] + 0.000058 x[0]*x[3]
 - 0.000004 x[0]*x[4] + 0.000158 x[0]*x[5] + 0.000010 x[0]*x[6]
 + 0.000171 x[0]*x[7] + 0.001042 x[1]^2 - 0.000033 x[1]*x[2]
 + 0.000227 x[1]*x[3] - 0.000075 x[1]*x[4] + 0.000588 x[1]*x[5]
 + 0.000509 x[1]*x[6] + 0.000035 x[1]*x[7] + 0.000099 x[2]^2
 - 0.000006 x[2]*x[3] + 0.000065 x[2]*x[4] - 0.000074 x[2]*x[5]
 - 0.000068 x[2]*x[6] + 0.000030 x[2]*x[7] + 0.000156 x[3]^2
 - 0.000021 x[3]*x[4] + 0.000244 x[3]*x[5] + 0.000155 x[3]*x[6]
 + 0.000120 x[3]*x[7] + 0.000091 x[4]^2 - 0.000109 x[4]*x[5]
 - 0.000096 x[4]*x[6] + 0.000018 x[4]*x[7] + 0.001647 x[5]^2
 + 0.000620 x[5]*x[6] + 0.000017 x[5]*x[7] + 0.000403 x[6]^2
 + 0.000014 x[6]*x[7] + 0.000170 x[7]^2 ] + 0.037500;

subject to {
 x[0] + x[1] + x[2] + x[3] + x[4] + x[5] + x[6] + x[7] == 3;

}
None

In [13]:
model.export_as_lp()

Warning: Some identifiers are not valid LP identifiers: 8 (e.g.: "x[0]")

'/tmp/combinatorial_portfolio_optimization.lp'

In [14]:
result = model.solve()

In [15]:
result.objective_value

-1.0791618691183933

In [16]:
result_array = np.array([result.get_value(f"x[{i}]") for i in range(len(tickers))])

In [17]:
result_array

array([0., 1., 1., 0., 0., 0., 1., 0.])

In [18]:
assets_close_price.columns[result_array.astype(bool)]

Index(['CCJ', 'JNJ', 'NVDA'], dtype='str', name='Ticker')

In [19]:
model = Model(name="combinatorial_portfolio_optimization")
x = np.array([model.binary_var(name=f"x[{i}]") for i in range(len(tickers))])
model.minimize(q*((x*weights_array).T@covariance_annualized.values@(x*weights_array))-(1-q)*(returns_annualized.values@x)+return_risk_free)
model.add_constraint(x.sum() <= b)
print(model.prettyprint())

// This file has been generated by DOcplex
// model name is: combinatorial_portfolio_optimization
// single vars section
dvar bool x[0];
dvar bool x[1];
dvar bool x[2];
dvar bool x[3];
dvar bool x[4];
dvar bool x[5];
dvar bool x[6];
dvar bool x[7];

minimize
 0.186768 x[0] - 0.575272 x[1] - 0.221385 x[2] - 0.140881 x[3] - 0.071102 x[4]
 + 0.304747 x[5] - 0.321957 x[6] + 0.003111 x[7] [ 0.000346 x[0]^2
 - 0.000019 x[0]*x[1] - 0.000032 x[0]*x[2] + 0.000058 x[0]*x[3]
 - 0.000004 x[0]*x[4] + 0.000158 x[0]*x[5] + 0.000010 x[0]*x[6]
 + 0.000171 x[0]*x[7] + 0.001042 x[1]^2 - 0.000033 x[1]*x[2]
 + 0.000227 x[1]*x[3] - 0.000075 x[1]*x[4] + 0.000588 x[1]*x[5]
 + 0.000509 x[1]*x[6] + 0.000035 x[1]*x[7] + 0.000099 x[2]^2
 - 0.000006 x[2]*x[3] + 0.000065 x[2]*x[4] - 0.000074 x[2]*x[5]
 - 0.000068 x[2]*x[6] + 0.000030 x[2]*x[7] + 0.000156 x[3]^2
 - 0.000021 x[3]*x[4] + 0.000244 x[3]*x[5] + 0.000155 x[3]*x[6]
 + 0.000120 x[3]*x[7] + 0.000091 x[4]^2 - 0.000109 x[4]*x[5]
 - 0.000096 x[4]*x[6] + 0.000018 x[4]*x[7] + 0.001647 x[5]^2
 + 0.000620 x[5]*x[6] + 0.000017 x[5]*x[7] + 0.000403 x[6]^2
 + 0.000014 x[6]*x[7] + 0.000170 x[7]^2 ] + 0.037500;

subject to {
 x[0] + x[1] + x[2] + x[3] + x[4] + x[5] + x[6] + x[7] <= 3;

}
None

In [20]:
result = model.solve()

In [21]:
result.objective_value

-1.0791618691183935

In [22]:
result_array = np.array([result.get_value(f"x[{i}]") for i in range(len(tickers))])

In [23]:
result_array

array([0., 1., 1., 0., 0., 0., 1., 0.])

In [24]:
assets_close_price.columns[result_array.astype(bool)]

Index(['CCJ', 'JNJ', 'NVDA'], dtype='str', name='Ticker')